namespace KONMediaProcessor.FFmpegExecutor;

using Domain.Exceptions;

/// <summary>
/// Executes FFmpeg or FFprobe commands.
/// </summary>
public interface IFFmpegExecutor
{
    /// <summary>
    /// Executes an FFmpeg command with the specified command path and arguments.
    /// </summary>
    /// <param name="commandPath">The path to the FFmpeg executable.</param>
    /// <param name="arguments">The arguments to be passed to the FFmpeg command.</param>
    /// <returns>The output generated by the FFmpeg command.</returns>
    /// <exception cref="FFmpegCommandExecutionException">Thrown when an error occurs during the execution of the FFmpeg command.</exception>
    string ExecuteCommand(string commandPath, string arguments);
}
