namespace KONMediaProcessor.FFmpegExecutor;

using Domain.Exceptions;
using Domain.Shared;

/// <summary>
/// Executes FFmpeg or FFprobe commands.
/// </summary>
internal interface IFFmpegExecutor
{
    /// <summary>
    /// Executes an FFmpeg command with the specified command path and arguments.
    /// </summary>
    /// <param name="executor">The executor that will be used to run the command if is ffmpeg or ffprobe</param>
    /// <param name="arguments">The arguments to be passed to the FFmpeg command.</param>
    /// <param name="cancellationToken">Cancellation token to stop the process</param>
    /// <returns>The output generated by the FFmpeg command.</returns>
    /// <exception cref="FFmpegCommandExecutionException">Thrown when an error occurs during the execution of the FFmpeg command.</exception>
    string ExecuteCommand(SupportedExecutors executor, string arguments, CancellationToken cancellationToken = default);
}
